export const langues = {
  fr: "Français",
  wo: "Wolof",
  en: "English",
};

export const traductions = {
  fr: {
    connexion: "Connexion",
    creerCompte: "Créer un compte",
    email: "Email",
    motDePasse: "Mot de passe",
    nom: "Nom",
    seConnecter: "Se connecter",
    sInscrire: "S'inscrire",
    pasDeCompte: "Pas encore de compte ?",
    dejaCompte: "Déjà un compte ?",
    mesBoutiques: "Mes boutiques",
    boutique: "boutique",
    boutiques: "boutiques",
    nouvelleBoutique: "Nouvelle boutique",
    parametres: "Paramètres",
    deconnexion: "Déconnexion",
    produitsEnStockBas: "produit(s) en stock bas",
    supprimer: "Supprimer",
    aucuneAdresse: "Aucune adresse",
    chargement: "Chargement...",
    aucuneBoutique: "Aucune boutique pour l'instant.",
    nouveauProduit: "Nouveau produit",
    clients: "Clients",
    retour: "Retour",
  },
  wo: {
    connexion: "Dugg",
    creerCompte: "Sos kont",
    email: "Imeel",
    motDePasse: "Baatu wet",
    nom: "Tur",
    seConnecter: "Dugg",
    sInscrire: "Sos kont",
    pasDeCompte: "Amoo kont ?",
    dejaCompte: "Am nga kont ?",
    mesBoutiques: "Sama bitig yi",
    boutique: "bitig",
    boutiques: "bitig",
    nouvelleBoutique: "Bitig bu bees",
    parametres: "Njangat",
    deconnexion: "Genn",
    produitsEnStockBas: "jumtukaay(i) sax stock bi wow",
    supprimer: "Far",
    aucuneAdresse: "Amul adres",
    chargement: "Di jottali...",
    aucuneBoutique: "Amul bitig fii.",
    nouveauProduit: "Jumtukaay bu bees",
    clients: "Kiliyaan yi",
    retour: "Delloo",
  },
  en: {
    connexion: "Login",
    creerCompte: "Create account",
    email: "Email",
    motDePasse: "Password",
    nom: "Name",
    seConnecter: "Log in",
    sInscrire: "Sign up",
    pasDeCompte: "No account yet?",
    dejaCompte: "Already have an account?",
    mesBoutiques: "My shops",
    boutique: "shop",
    boutiques: "shops",
    nouvelleBoutique: "New shop",
    parametres: "Settings",
    deconnexion: "Log out",
    produitsEnStockBas: "product(s) low on stock",
    supprimer: "Delete",
    aucuneAdresse: "No address",
    chargement: "Loading...",
    aucuneBoutique: "No shop yet.",
    nouveauProduit: "New product",
    clients: "Customers",
    retour: "Back",
  },
};

export function useTraduction(langue) {
  return (cle) => traductions[langue]?.[cle] || traductions.fr[cle] || cle;
}